In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [6]:
lst = [1,2,3,4]
print(lst)
print(type(lst))
print("="*30)
s = np.array(5)
print(s)
print("="*30)
v= np.array([1,2,3,4])
print(v)
print("="*30)
m = np.array([
[1,2,3],
[4,5,6],
[7,8,9]
])
print(m)


[1, 2, 3, 4]
<class 'list'>
5
[1 2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
s = np.array(5)
#print(s)
print(s.ndim)
print(s.shape)
print("="*30)
v= np.array([1,2,3,4])
#print(v)
print(v.ndim)
print(v.shape)
print("="*30)
m = np.array([
[1,2,3],
[4,5,6],
[7,8,9]
])
#print(m)
print(m.ndim)
print(m.shape)


0
()
1
(4,)
2
(3, 3)


In [13]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
mat


array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
vec = np.array([1,2,3,4,5,6])
print(vec.shape)
print(vec.shape[0])
print(vec.shape[1])
#mat = vec.

(6,)
6


IndexError: tuple index out of range

In [19]:
vec = np.array([1,2,3,4,5,6])
print(m.shape)
print(m.shape[0])
print(m.shape[1])

(3, 3)
3
3


In [20]:
vec = np.array([1,2,3,4])
mat = vec.reshape(vec.shape[0],1)
mat

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
# another way of reshape to column vector
vec = np.array([1,2,3,4])
mat = vec[:,None]
mat

array([[1],
       [2],
       [3],
       [4]])

In [26]:
def array_reshape(arr , rows , cols):
    try:
        arr = np.array(arr)       # convert lst to array  as v1=np.array(lst)
        return arr.reshape(rows,cols)
    
    except(TypeError,ValueError):
        raise ValueError(f" invalid reshape operation:{e}")


In [24]:
vec = [1,2,3,4,5,6]
array_reshape(vec,2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
array_reshape(vec,2,7)

NameError: name 'e' is not defined

In [30]:
mat = np.array([
    [1.1,2,3],
    [4,5,6],
    [7,8,9]
])
print(mat.dtype)
print(mat)

float64
[[1.1 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [31]:
mat = np.array([
    [1.1,'2',3],
    [4,5,6],
    [7,8,9]
])
print(mat.dtype)
print(mat)

<U32
[['1.1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


In [34]:
class c:
    x=3

o1= c()

In [35]:
mat = np.array([
    [1.1,'2',o1],
    [4,5,6],
    [7,8,9]
])
print(mat.dtype)
print(mat)

object
[[1.1 '2' <__main__.c object at 0x00000275CE1D3940>]
 [4 5 6]
 [7 8 9]]


In [36]:
mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
fmat= mat.astype(float)
print(fmat.dtype)
print(fmat)

float64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [37]:
mat = np.array([
    [1,2.1,3],
    [4,5.6,6],
    [7,8,9]
])
fmat= mat.astype(int)
print(fmat.dtype)
print(fmat)

int32
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
mat = np.array([
    [1,2.1,"test"],
    [4,5,6],
    [7,8,9]
])
fmat= mat.astype(int)
print(fmat.dtype)
print(fmat)

ValueError: invalid literal for int() with base 10: '2.1'

In [39]:
def convert_dtype(ar, dtype):
    try:
        arr = np.array(arr)
        return arr.astype(dtype)
    except TypeError as e:
        raise TypeError(f" invalid target data type:{dtype}") from e

   

In [40]:
v = np.array([1,2,3,5,1])
v[1]

2

In [45]:
mat = np.array([
    [1,2,2],
    [4,5,6],
    [7,8,9],
    [0,0,0]
])
print(mat[1,2])
print(mat[1:3,0:2])
print(mat[-3:1,-3:-1])
print(mat.T)

6
[[4 5]
 [7 8]]
[]
[[1 4 7 0]
 [2 5 8 0]
 [2 6 9 0]]


In [46]:
mat = np.zeros((3,4))
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
mat = np.ones((3,4))
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
mat = np.full((3,4),6)
mat

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [49]:
def init_arr(shape,value = 0):
    return np.full(shape, value)


In [53]:
zeros = init_arr((3,4))
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [1]:
import numpy as np
np.random.random((3,3))

array([[0.37331938, 0.98963147, 0.92603807],
       [0.99804665, 0.93559119, 0.87218428],
       [0.93249383, 0.23774195, 0.17131867]])

In [2]:
np.random.randint(0,11,(5,5))

array([[ 5,  6,  1, 10, 10],
       [ 0,  1, 10,  1,  2],
       [ 7,  0,  6,  3,  8],
       [ 5,  9,  3,  8,  5],
       [ 5, 10,  3,  4,  0]])

In [3]:
a= ["ali",3,"omar",False]
np.random.choice(a, size=(3,5))

array([['omar', 'omar', '3', 'False', 'ali'],
       ['omar', 'ali', 'False', '3', 'ali'],
       ['ali', 'ali', 'omar', 'False', 'ali']], dtype='<U11')

In [4]:
mat1 = np.ones((3,4))
mat2 = np.zeros((5,3))

np.savez("file.npz", Ones_mat = mat1, Zeros_mat = mat2)


In [6]:
with np.load("file.npz") as file:
    mat1 = file["Ones_mat"]
    mat2 = file["Zeros_mat"]

    print(mat1)
    print("="*30)
    print(mat2)
   

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
m1= np.array([1,2,3 ])
m2= np.array([4,5,6])
print(np.vstack((m1,m2)))
print(np.hstack((m1,m2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [10]:
v = np.array([1,3,4,5,0])
np.all(v>=1)

False

In [11]:
v = np.array([1,2,3,4,5])
np.any(v==1)

True

In [12]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])
np.isclose(v1,v2,atol=1)

array([ True,  True, False,  True, False])

In [13]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])
np.allclose(v1,v2,atol=1)

False

In [14]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,2,5,4])
np.allclose(v1,v2,atol=1)

True

In [15]:
v1 = np.array([1,2,3,4,5])
condition = (v1>=4)
print(condition)



[False False False  True  True]


In [16]:
v1 = np.array([1,2,3,4,5])
condition = (v1>=4)
v[condition] =-1
print(v)

[ 1  2  3 -1 -1]


In [17]:
v1 = np.array([1,2,3,4,5])
condition = (v1>=4)
new_arr = np.where(condition ,-1,v)
print(new_arr)

[ 1  2  3 -1 -1]
