## Numpy programming assignment

In [4]:
# problem 1
import numpy as np

def array_factory(mode, shape, value=None):
    if mode == "zeros":
        return np.zeros(shape)
    
    elif mode == "ones":
        return np.ones(shape)
    
    elif mode == "full":
        return np.full(shape, value)
    
    elif mode == "identity":
        return np.identity(shape)
    
    else:
        raise ValueError("Invalid mode")


array = array_factory("zeros",(3,4))
print(array)

print("===========")

array1 = array_factory("ones",(4,4))
print(array1)


print("===========")

array2 = array_factory("full",(3,3),5)
print(array2)


print("===========")

array3 = array_factory("identity",4)
print(array3)





[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# problem 2
def secure_reshape_and_stack(data1, data2, new_shape):
    try:
        arr1= np.array(data1)
        arr2= np.array(data2)

        reshaped_arr1= np.reshape(arr1, new_shape)
       
        combined_matrices= np.vstack((reshaped_arr1, arr2))
        return combined_matrices
    except ValueError as e:
        raise ValueError (f" company-grade Error: {e}")

    
data1 = [1, 2, 3, 4, 5, 6]

data2 = [
    [7, 8, 9],
    [10, 11, 12]
]

test1 = secure_reshape_and_stack(data1, data2, (2, 3))

print(test1)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
